#!/usr/bin/env python3
"""Generate a C++ source embedding one binary file, deflated.

Same shape as embed_firmware.py and for the same reason: this app ships as a
single executable, and a recovery diagram that lived beside it as a loose file
would be the one thing missing exactly when somebody is trying to recover a
board. zlib deflates here; miniz inflates at runtime with
TINFL_FLAG_PARSE_ZLIB_HEADER (see fwBoardImage.cpp).

Usage: embed_resource.py <input-file> <symbol> <out-dir>

Writes <out-dir>/fwEmbeddedResource_<symbol>.cpp defining, in namespace fwog:

    std::span<const unsigned char> <symbol>Deflated();
    std::size_t                    <symbol>RawSize();

A MISSING INPUT IS AN ERROR, not a warning. embed_firmware.py tolerates absent
UF2s because only release builds need the real firmware; there is no equivalent
here -- an absent diagram is a typo in the build, and emitting a zero-byte
resource would turn that into a blank panel at runtime instead of a build
failure.

This script is invoked by an ALWAYS-RUN build step (see cmake/EmbedResources.
cmake for why), so it owns its own up-to-date check, exactly as
embed_firmware.py does:

  * it hashes its inputs into a stamp file and returns immediately, having
    deflated nothing, when the stamp still matches;
  * it writes the .cpp only when the content actually changes, so an ordinary
    build does not recompile the 3.7 MB translation unit or relink the app;
  * the stamp is written LAST, so an interrupted run leaves a stamp that does
    not match and the next build regenerates rather than trusting half-written
    output.
"""
import hashlib
import sys
import zlib
from pathlib import Path

# Bump when the shape of the emitted C++ changes in a way that an existing
# output would not reflect. Hashing this script's own bytes below covers that
# too; the tag is here so the reason is legible in the stamp file when someone
# opens it.
GENERATOR_ID = "fwog-embed-resource/1"


def sha256_file(path):
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def input_stamp(script_path, src, symbol):
    """Hash every byte this generator reads, plus the arguments that shape it.

    Deliberately CONTENT, not timestamps -- see cmake/EmbedResources.cmake.
    `symbol` and the input's file NAME are in here because both are written
    into the generated source, so either changing has to regenerate even when
    the bytes being embedded do not.
    """
    return "\n".join([
        GENERATOR_ID,
        "generator " + sha256_file(script_path),
        "symbol " + symbol,
        "input {} {}".format(src.name, sha256_file(src)),
    ]) + "\n"


def write_if_different(path, text):
    """Write only on a real content change; report whether it wrote.

    Returning early keeps the file's mtime where it was, which is what stops an
    always-run generator from recompiling and relinking everything downstream.
    """
    data = text.encode("utf-8")
    try:
        if path.read_bytes() == data:
            return False
    except OSError:
        pass
    path.write_bytes(data)
    return True


def c_array(name, data):
    out = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        out.append("    " + chunk + ",")
    out.append("};")
    return "\n".join(out)


def main():
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <input-file> <symbol> <out-dir>")
    script_path = Path(__file__).resolve()
    src, symbol, out_dir = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])
    if not src.is_file():
        sys.exit(f"embed_resource.py: no such file: {src}")

    out_dir.mkdir(parents=True, exist_ok=True)
    source = out_dir / f"fwEmbeddedResource_{symbol}.cpp"
    stamp = out_dir / f"fwEmbeddedResource_{symbol}.stamp"

    want_stamp = input_stamp(script_path, src, symbol)
    # The output has to exist as well as the stamp matching: a stamp alone would
    # happily declare a deleted .cpp up to date.
    if source.is_file() and stamp.is_file() and stamp.read_text() == want_stamp:
        return

    raw = src.read_bytes()
    deflated = zlib.compress(raw, 9)

    body = f"""// GENERATED by tools/embed_resource.py from {src.name} -- do not edit.
#include <cstddef>
#include <span>

namespace fwog {{
namespace {{
{c_array(symbol + "_deflated", deflated)}
}} // namespace

std::span<const unsigned char> {symbol}Deflated()
{{
    return std::span<const unsigned char>({symbol}_deflated, sizeof({symbol}_deflated));
}}

std::size_t {symbol}RawSize() {{ return {len(raw)}u; }}

}} // namespace fwog
"""
    wrote = write_if_different(source, body)

    # LAST, and only now: the output above is actually on disk.
    stamp.write_text(want_stamp)
    print(f"embed_resource.py: {src.name} {len(raw)} -> {len(deflated)} bytes deflated; "
          + (f"wrote {source.name}" if wrote else "generated output unchanged"))


if __name__ == "__main__":
    main()
