#!/usr/bin/env python3
"""Generate fwEmbeddedFirmware.{h,cpp} from firmware/manifest.json.

Deflates each UF2 with zlib (miniz inflates it at runtime with
TINFL_FLAG_PARSE_ZLIB_HEADER) and records size + SHA-256 so the app can verify
what it embedded. A missing image is a warning, not an error: only release
builds need the real files.

Usage: embed_firmware.py <firmware-dir> <out-dir>
"""
import hashlib
import json
import sys
import zlib
from pathlib import Path


def c_array(name, data):
    out = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        out.append("    " + chunk + ",")
    out.append("};")
    return "\n".join(out)


def main():
    fw_dir, out_dir = Path(sys.argv[1]), Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    manifest_path = fw_dir / "manifest.json"
    manifest = json.loads(manifest_path.read_text()) if manifest_path.exists() else {}

    blobs, meta = [], []
    available = set()
    for img in manifest.get("images", []):
        # "file" is resolved relative to the firmware directory and MAY reach
        # outside it. Exactly one image does: "fwog_probe" lives at
        # ../probe/probe.uf2, because it is the only .uf2 in this repo that is
        # committed to git and it belongs beside the probe/probe.c it was built
        # from, not in the directory whose contents are deliberately absent (see
        # .gitignore). manifest.json is a source file in this repository -- it
        # never comes from a catalog or a download -- so a relative path here is
        # a repo-layout statement, not untrusted input.
        path = fw_dir / img["file"]
        if not path.exists():
            print(f"warning: {path} not found; skipping embedded image "
                  f"{img['id']!r}", file=sys.stderr)
            continue
        raw = path.read_bytes()
        sym = "k_" + img["id"].replace("-", "_")
        blobs.append(c_array(sym, zlib.compress(raw, 9)))
        meta.append({
            "id": img["id"], "sym": sym, "version": img.get("version", ""),
            "size": len(raw), "sha256": hashlib.sha256(raw).hexdigest(),
        })
        available.add(img["id"])

    # Drop entries whose images are not all present, so the app never offers a
    # firmware it cannot actually write.
    entries = [e for e in manifest.get("entries", [])
               if all(a["id"] in available for a in e.get("uf2", []))]

    # parseCatalogJson (Task 7) reads "embeddedId" inside each uf2 object, not
    # "id" -- rewrite the key so the generated catalog is resolvable.
    for e in entries:
        for a in e.get("uf2", []):
            if "id" in a:
                a["embeddedId"] = a.pop("id")

    header = out_dir / "fwEmbeddedFirmware.h"
    header.write_text(
        "// Generated by tools/embed_firmware.py. Do not edit.\n"
        "#pragma once\n"
        "#include <cstddef>\n#include <cstdint>\n#include <string>\n#include <vector>\n\n"
        "namespace fwog::generated {\n\n"
        "struct EmbeddedImage {\n"
        "    const char*          id;\n"
        "    const char*          version;\n"
        "    const unsigned char* deflated;\n"
        "    std::size_t          deflatedSize;\n"
        "    std::size_t          rawSize;\n"
        "    const char*          sha256;\n"
        "};\n\n"
        "extern const EmbeddedImage* const kImages;\n"
        "extern const std::size_t         kImageCount;\n"
        "/// firmware/manifest.json's \"entries\" array, verbatim.\n"
        "extern const char* const         kEntriesJson;\n\n"
        "} // namespace fwog::generated\n")

    body = ["// Generated by tools/embed_firmware.py. Do not edit.",
            '#include "fwEmbeddedFirmware.h"', "",
            "namespace fwog::generated {", "namespace {", ""]
    body += blobs
    body += ["", "const EmbeddedImage kTable[] = {"]
    for m in meta:
        body.append(f'    {{ "{m["id"]}", "{m["version"]}", {m["sym"]}, '
                    f'sizeof({m["sym"]}), {m["size"]}, "{m["sha256"]}" }},')
    if not meta:
        body.append("    { nullptr, nullptr, nullptr, 0, 0, nullptr },")
    body += ["};", "", "} // namespace", ""]

    entries_json = json.dumps({"apps": entries}, separators=(",", ":"))
    escaped = entries_json.replace("\\", "\\\\").replace('"', '\\"')

    body += [f"const EmbeddedImage* const kImages = kTable;",
             f"const std::size_t kImageCount = {len(meta)};",
             f'const char* const kEntriesJson = "{escaped}";', "",
             "} // namespace fwog::generated"]

    (out_dir / "fwEmbeddedFirmware.cpp").write_text("\n".join(body) + "\n")
    print(f"embedded {len(meta)} image(s), {len(entries)} entry(ies)")


if __name__ == "__main__":
    main()
