#!/usr/bin/env python3
"""Generate a C++ source embedding one binary file, deflated.

Same shape as embed_firmware.py and for the same reason: this app ships as a
single executable, and a recovery diagram that lived beside it as a loose file
would be the one thing missing exactly when somebody is trying to recover a
board. zlib deflates here; miniz inflates at runtime with
TINFL_FLAG_PARSE_ZLIB_HEADER (see fwBoardImage.cpp).

Usage: embed_resource.py <input-file> <symbol> <out-dir>

Writes <out-dir>/fwEmbeddedResource_<symbol>.cpp defining, in namespace fwog:

    std::span<const unsigned char> <symbol>Deflated();
    std::size_t                    <symbol>RawSize();

A MISSING INPUT IS AN ERROR, not a warning. embed_firmware.py tolerates absent
UF2s because only release builds need the real firmware; there is no equivalent
here -- an absent diagram is a typo in the build, and emitting a zero-byte
resource would turn that into a blank panel at runtime instead of a build
failure.
"""
import sys
import zlib
from pathlib import Path


def c_array(name, data):
    out = [f"static const unsigned char {name}[] = {{"]
    for i in range(0, len(data), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 16])
        out.append("    " + chunk + ",")
    out.append("};")
    return "\n".join(out)


def main():
    if len(sys.argv) != 4:
        sys.exit(f"usage: {sys.argv[0]} <input-file> <symbol> <out-dir>")
    src, symbol, out_dir = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])
    if not src.is_file():
        sys.exit(f"embed_resource.py: no such file: {src}")

    raw = src.read_bytes()
    deflated = zlib.compress(raw, 9)
    out_dir.mkdir(parents=True, exist_ok=True)

    body = f"""// GENERATED by tools/embed_resource.py from {src.name} -- do not edit.
#include <cstddef>
#include <span>

namespace fwog {{
namespace {{
{c_array(symbol + "_deflated", deflated)}
}} // namespace

std::span<const unsigned char> {symbol}Deflated()
{{
    return std::span<const unsigned char>({symbol}_deflated, sizeof({symbol}_deflated));
}}

std::size_t {symbol}RawSize() {{ return {len(raw)}u; }}

}} // namespace fwog
"""
    (out_dir / f"fwEmbeddedResource_{symbol}.cpp").write_text(body, encoding="utf-8")
    print(f"embed_resource.py: {src.name} {len(raw)} -> {len(deflated)} bytes deflated")


if __name__ == "__main__":
    main()
